### PR TITLE
Add support for changing the area radius

### PR DESCRIPTION
**Pull request by johrpan**
This adds support for customizing the area radius in a backwards compatible fashion. Old game links will still result in the default radius being used. The user visible changes include the additional part of the URL path as well as a slider for controlling the radius.

An open question that needs to be discussed is how to handle the points. Obviously it is much easier to get high scores with a smaller area. So, in the current state of this PR, scores aren't comparable between different rounds anymore. When sharing game links this is not an issue due to the radius being included. But the personal high score will be influenced.

Also, I am not a web developer. I tried to match the slider style to the other controls and tested it using Firefox and Chromium. But there might be room for improvement.

### CODE REVIEW

**Comment by adam-lynch** [comment]
I'll dig into this at the weekend, thanks!

**Comment by johrpan** [comment]
Don't worry and don't feel obliged to look into it soon. I can wait! Just figured I would put this here as I had it kind of done for my own use.

**Comment by adam-lynch** [comment]
Thanks so much for this! This will take a little bit more back-and-forth as you guessed, but here's my initial feedback...

You did a great job with the UI, it looks great. A nice little detail would be if the slider thumb/circle changed colour on hover, if possible.

I made this with phones and tablets in mind first, followed by larger screens. I wonder does it take up too much space on a phone. Maybe we should have a settings button which opens a modal / accordion?

You shouldn't need any CSS vendor-prefixes like `-webkit`. You should be able to write the CSS rule once without any prefixes and the build system should add it if needed. Please correct me if I'm wrong.

---

I like that when you increase the radius, the map zooms out. I wish it zoomed in when you decrease the radius but it doesn't. But maybe this would happen if #39 was implemented and you wouldn't need to change anything in this PR, not sure.

When the radius is less than 500m, the dot / smaller circle I added to the centre of the circle makes it look funny. Ideas:

- Hide it depending on the radius size.
- Change it visually so it looks OK at any radius, e.g. reduce opacity maybe.

---

My gut reaction to the URL update is that I don't love it. Of course you're following the existing pattern and it's great that it's backwards-compatible, etc. I went for this unorthodox URL pattern originally to keep it short and "nice" (side note: it made things a little more difficult to implement).

Now that more things will be added to the game (e.g. radius, difficulty, etc), my gut says not to keep adding stuff into this URL pattern. I can't think of a nice solution for it right now;

- This pattern.
- `?radius=500` query parameter.
- Encode this (and other future settings) into the seed URL segment. E.g. base64 or something like that. Or it could be that we append a single digit to the seed string which indicates zoom level.

Whatever we do, I'd like it to be backwards-compatible, so I don't want to rush into the wrong thing. You persist the radius to localStorage so it will be saved for future; the remaining reasons for having it in the URL would be:

- You can share the URL with someone else and the other person gets your radius.
- You can bookmark the URL if you play multiple areas with varying radius. Not a big concern in my opinion.

I think we could release this feature without it being in the URL. I don't think the URL needs to block this.

However, I might be underestimating the importance of sharing the seed with the radius. Or maybe it wouldn't be too difficult to settle on a pattern that could handle future settings. What do you think?

---

>An open question that needs to be discussed is how to handle the points. Obviously it is much easier to get high scores with a smaller area. So, in the current state of this PR, scores aren't comparable between different rounds anymore. When sharing game links this is not an issue due to the radius being included. But the personal high score will be influenced.

I wouldn't worry about this too much for now. There isn't a clear answer in my opinion and we can see what people say before improving it. This would be more important if there were leaderboards comparing scores for example.

---

To be clear, I'm happy to help code any of these suggestions if you need

**Comment by johrpan** [comment]
> You did a great job with the UI, it looks great. A nice little detail would be if the slider thumb/circle changed colour on hover, if possible.

I used the same background colors as the `button--primary` class. So, at least in my browser, it does change color slightly. But of course we can increase the difference, if you like.

> I made this with phones and tablets in mind first, followed by larger screens. I wonder does it take up too much space on a phone. Maybe we should have a settings button which opens a modal / accordion?

I think, if more settings are added, this will be a good approach. At the moment, it seems like the aspect ratio of the map above the panel is still more than 1:1, which I would consider good enough. When playing the game, the slider will disappear anyway.

> You shouldn't need any CSS vendor-prefixes like `-webkit`. You should be able to write the CSS rule once without any prefixes and the build system should add it if needed. Please correct me if I'm wrong.

As far as I know, there is no standard selector for styling the slider thumb. I don't know whether it is possible to make use of the tooling in that case.
 
> I like that when you increase the radius, the map zooms out. I wish it zoomed in when you decrease the radius but it doesn't. But maybe this would happen if #39 was implemented and you wouldn't need to change anything in this PR, not sure.

I didn't do anything, it just worked like that out of the box. But I also think that #39 will fix this, at least if the "flight" is targeted to the circle.

> When the radius is less than 500m, the dot / smaller circle I added to the centre of the circle makes it look funny. Ideas:
> 
>     * Hide it depending on the radius size.
> 
>     * Change it visually so it looks OK at any radius, e.g. reduce opacity maybe.

In my opinion, the dot shouldn't be hidden, because it's the only indicator for choosing where to tap to move the area to the desired location – especially for small adjustments. I'll go ahead and try to make the circle size relative to the radius of the area

I'll think about the URL afterwards.

**Comment by johrpan** [comment]
Side note: There might be an issue with a tracking pixel. It will be fetched every time the area is updated (also previously) meaning that lots of requests will be sent when dragging the slider. I don't know whether that is the desired behavior.

**Comment by adam-lynch** [comment]
I see the hover style now, my bad.

>I think, if more settings are added, this will be a good approach. At the moment, it seems like the aspect ratio of the map above the panel is still more than 1:1, which I would consider good enough. When playing the game, the slider will disappear anyway.

OK, I'm convinced.

>As far as I know, there is no standard selector for styling the slider thumb. I don't know whether it is possible to make use of the tooling in that case.

OK, fair enough then.

>In my opinion, the dot shouldn't be hidden, because it's the only indicator for choosing where to tap to move the area to the desired location – especially for small adjustments. I'll go ahead and try to make the circle size relative to the radius of the area

It looks good!

>Side note: There might be an issue with a tracking pixel. It will be fetched every time the area is updated (also previously) meaning that lots of requests will be sent when dragging the slider. I don't know whether that is the desired behavior.

Thanks, I've fixed this just now on the `main` branch.

**Comment by adam-lynch** [comment]
OK I've just finished #39; https://github.com/adam-lynch/back-of-your-hand/commit/821e1814b474ed00165b33cb5ce11d94ad83959c. If you pull that into your branch, it should zoom in when decreasing the radius

---

I spent a long time on it because I didn't like how the map would have to zoom when the page is loaded if a custom radius was used. I.e. it could load the map tiles needed for the initial zoom, then it would change the zoom level and load more tiles. It means there are more request and it doesn't look nice.

But it seems like there's no way to compute the initial zoom without initializing the map first, so I'm just going to live with it.

Anyway, this stuff depends a bit on the screen size anyway. At least now the circle will be the same size relative to the viewport on any device.

---

I also looked into making the radius update little glitchy and I couldn't find a better way (e.g. updating the radius rather than redrawing the circle, using a CircleMarker vs a circle, etc). Using `map.flyToBounds` rather than `map.fitBounds` does make it somewhat smoother. It's still not perfect but it's better.

**Comment by johrpan** [comment]
I rebased the branch on your main branch. The new behavior isn't smooth all the times, but looks like an improvement to me.

**Comment by johrpan** [comment]
Concerning the URL:

Thinking more about it, backwards compatibility probably isn't top priority. It's not difficult to set up a similar game again once, if some old link breaks (in case of having a game link bookmarked) and sharing links will probably be an ephemeral action anyway.

The obvious approach (that would also simplify adding more settings in the future) would be to use query parameters as you suggested. Everything that is not present will result in default values being applied. The seed should stay separate in my opinion, because there is the valid use case of having a bookmarked link with custom settings to replay in the same area. If we switch to query parameters, the URLs will probably look better, if either all parameters or everything besides the coordinates will also move to the query parameter section. This would result in the following options:

1. `https://backofyourhand.com/54.08764,12.1393?radius=1000&seed=abcde
2. `https://backofyourhand.com/?lat=54.08764&lng=12.1393&radius=1000&seed=abcde

**Comment by adam-lynch** [comment]
>I rebased the branch on your main branch. The new behavior isn't smooth all the times, but looks like an improvement to me.

I agree.

>Concerning the URL:

Good stuff, thanks for thinking this through. Using all query parameters really is the best because it's the most flexible. It inspired me to make a pull-request (#44) to support query parameters which this PR could extend further. In doing it, I found that making it backwards-compatible wasn't actually too difficult. Which is good as you say for the bookmark use case.

I've tested it and it seems good, but to be extra safe, could you give it a test? You can use https://dc13f641.backofyourhand.pages.dev. Because this is a new (sub)domain, you won't have anything in localStorage. Please note that the latitude & longitude are saved to localStorage if you complete one round.

So if that's OK, we can merge that PR first. Then this PR can be updated to similarly parse the radius from the URL and set it in the URL. Then we're good to merge this 😁

**Comment by adam-lynch** [comment]
I've merged and deployed the changes to the URL, i.e. the site uses query parameters now

**Comment by adam-lynch** [comment]
Let me know if I can help with this pull-request in any way

**Comment by johrpan** [comment]
I'll try to merge the changes from main into my branch later today. Besides that, it's ready in my opinion. Do you have any remaining issues?

**Comment by adam-lynch** [comment]
No, all good. I've just merged it; it'll be live in a couple of minutes (hard refresh if you don't see it). 

Again, thanks so much for doing this!! I'm sure players will really appreciate it too!

**Comment by adam-lynch** [comment]
Hi @johrpan,

I hope you’re well. Thanks again for contributing, I really appreciate it.

## License Change

I’m currently overhauling this project and in doing that, I decided to change the license. Currently, it’s licensed under the [MIT License](https://choosealicense.com/licenses/mit/) and I am planning to re-license the project under the [Mozilla Public License 2.0 (MPL 2.0)](https://choosealicense.com/licenses/mpl-2.0/).

## Your consent

I would like your permission to re-license your contributions under MPL 2.0. All I ask is that you reply and confirm your consent. If you have any concerns or prefer not to re-license your contributions, please let me know (my email is on [my profile](https://github.com/adam-lynch/) if you would prefer that).

I will be re-licensing all of my contributions and will keep yours under MIT until you provide your consent to re-license them under MPL 2.0.

## Your contributions

All of your contributions are contained in this pull-request.

## Why MPL 2.0?

1. **File-Level Copyleft**: Ensures improvements are shared back with the community.
2. **Compatibility**: MPL 2.0 works well with other licenses, including GPL, allowing easier integration with larger projects.
3. **Contributor Management**: Provides clear guidelines for contributions and obligations.
4. **Patent Protection**: Offers explicit patent grants, protecting contributors from patent litigation.
5. **Balanced Copyleft**: Encourages open-source contributions while permitting use in proprietary projects under specific conditions.
6. **Corporate Adoption**: Aligns better with some corporate open-source policies.
7. **Clearer Compliance**: Known for precise language, making legal compliance simpler.

## More information

- [MIT License](https://choosealicense.com/licenses/mit/)
- [Mozilla Public License 2.0 (MPL 2.0)](https://choosealicense.com/licenses/mpl-2.0/)

Thank you!

**Comment by johrpan** [comment]
Hello! I confirm my consent to the planned license change. No problem!

**Comment by adam-lynch** [comment]
Thank you!

**Pull request merged**
